packages:
  github.com/e2b-dev/infra/packages/envd/internal/services/spec/filesystem/filesystemconnect:
    interfaces:
      FilesystemHandler:
        config:
          dir: packages/envd/internal/services/spec/filesystem/filesystemconnect/mocks
          filename: mocks.go
          pkgname: filesystemconnectmocks

  github.com/e2b-dev/infra/packages/shared/pkg/storage:
    interfaces:
      featureFlagsClient:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_featureflagsclient_test.go
          pkgname: storage
          inpackage: true
          structname: MockFeatureFlagsClient
      Blob:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_blob_test.go
          pkgname: storage
          inpackage: true
      FramedFile:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_framedfile_test.go
          pkgname: storage
          inpackage: true

  io:
    interfaces:
      Reader:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_ioreader_test.go
          pkgname: storage
          inpackage: true

  github.com/e2b-dev/infra/packages/shared/pkg/utils:
    interfaces:
      fileOps:
        config:
          dir: packages/shared/pkg/utils
          filename: mocks_test.go
          pkgname: utils

  github.com/e2b-dev/infra/packages/api/internal/handlers:
    interfaces:
      featureFlagsClient:
        config:
          dir: packages/api/internal/handlers/mocks
          filename: mockfeatureflagsclient.go
          pkgname: handlersmocks
          structname: MockFeatureFlagsClient

  github.com/willscott/go-nfs:
    interfaces:
      Handler:
        config:
          dir: packages/orchestrator/internal/nfsproxy/mocks
          filename: nfshandler.go
          pkgname: nfsproxymocks

  github.com/go-git/go-billy/v5:
    interfaces:
      Change:
        config:
          dir: packages/orchestrator/internal/nfsproxy/mocks
          filename: billychange.go
          pkgname: nfsproxymocks
      File:
        config:
          dir: packages/orchestrator/internal/nfsproxy/mocks
          filename: billyfile.go
          pkgname: nfsproxymocks
      Filesystem:
        config:
          dir: packages/orchestrator/internal/nfsproxy/mocks
          filename: billyfs.go
          pkgname: nfsproxymocks
